### ISSUE TITLE
Responsive Design?

### ISSUE THREAD

**Issue by anlek** [Wanderxx/vue-fullcalendar#4]
Any plans to make the calendar responsive? I'm trying to make it work on mobile. (similar to: http://fullcalendar.io/js/fullcalendar-2.9.1/demos/agenda-views.html)

**Comment by anlek** [comment]
Quick fix for me was to do this with CSS:

``` CSS
  .comp-full-calendar{
    width: auto !important;
  }
```

It's not perfect but it works for now.
